version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: designer-portfolio-db
    environment:
      POSTGRES_DB: designer_portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - designer-portfolio-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: designer-portfolio-backend
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: designer_portfolio
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - designer-portfolio-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: designer-portfolio-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - designer-portfolio-network

volumes:
  postgres_data:

networks:
  designer-portfolio-network:
    driver: bridge